services:
  mongodb:
    image: mongo:7
    container_name: ai_sinav_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ai_sinav_db
    restart: unless-stopped

  auth-service:
    build: ./services/auth-service
    container_name: ai_sinav_auth
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongodb:27017/ai_sinav_db
      JWT_SECRET: ai-mulakat-test-secret-key-2026-gizli-anahtar
      JWT_EXPIRES_IN: 7d
      JWT_REFRESH_SECRET: ai-mulakat-refresh-secret-key-2026-yenile
      JWT_REFRESH_EXPIRES_IN: 30d
      NODE_ENV: development
      INSTRUCTOR_SECRET_CODE: EGITMEN-AI-2024
    depends_on:
      - mongodb
      - face-detection
      - eye-tracking
      - audio-analysis
      - risk-scoring
    restart: unless-stopped

  face-detection:
    build: ./ai-services/face-detection-service
    container_name: ai_sinav_face
    ports:
      - "8091:8091"
    restart: unless-stopped

  eye-tracking:
    build: ./ai-services/eye-tracking-service
    container_name: ai_sinav_eye
    ports:
      - "8092:8092"
    restart: unless-stopped

  audio-analysis:
    build: ./ai-services/audio-analysis-service
    container_name: ai_sinav_audio
    ports:
      - "8093:8093"
    restart: unless-stopped

  risk-scoring:
    build: ./ai-services/risk-scoring-service
    container_name: ai_sinav_risk
    ports:
      - "8094:8094"
    restart: unless-stopped

  exam-service:
    build: ./services/exam-service
    container_name: ai_sinav_exam
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGO_URI: mongodb://mongodb:27017/ai_sinav_db
      NODE_ENV: development
    depends_on:
      - mongodb
    restart: unless-stopped

  reporting-service:
    build: ./services/reporting-service
    container_name: ai_sinav_reporting
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGO_URI: mongodb://mongodb:27017/ai_sinav_db
      NODE_ENV: development
    depends_on:
      - mongodb
    restart: unless-stopped

  proctoring-service:
    build: ./services/proctoring-service
    container_name: ai_sinav_proctoring
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      MONGO_URI: mongodb://mongodb:27017/ai_sinav_db
      NODE_ENV: development
      FACE_SERVICE_URL: http://face-detection:8091
      EYE_SERVICE_URL: http://eye-tracking:8092
      AUDIO_SERVICE_URL: http://audio-analysis:8093
      RISK_SERVICE_URL: http://risk-scoring:8094
      AI_REQUEST_TIMEOUT_MS: 6000
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
